### PR TITLE
Feature redeem voucher UI

### PR DESCRIPTION
**Pull request by Mohammed-Nazar**
Done with Redeem voucher landing page

### CODE REVIEW

**Comment by amnah44** [comment]
Can you please fix the conflict here.

**Comment by Mohammed-Nazar** [comment]
@amnah44 Done with fixing the conflict can you merge it please?

**Comment by amnah44** [comment]
@Mohammed-Nazar Please fix the conflict again to marge it.

**Comment by Mohammed-Nazar** [comment]
@amnah44 Done

**Pull request merged**
